### ISSUE TITLE
Please correct from "/topic/" to "/topics/"

### ISSUE THREAD

**Issue by ImaginativeShohag** [jewel-rana/easy-firebase-push#1]
It should be "/topics/" in the following line:

https://github.com/jewel-rana/easy-firebase-push/blob/2b3f055e7455a4d895d1f8b558c6fc2aaa81e0e8/src/FirebaseController.php#L125

From the doc: (https://firebase.google.com/docs/cloud-messaging/http-server-ref)

> The value can be a device's registration token, a device group's notification key, or a single topic (prefixed with /topics/). To send to multiple topics, use the condition parameter.

**Comment by jewel-rana** [comment]
Your issue resolved, Thanks
